### ISSUE TITLE
Cambio de dirección I2C del sensor de flujo

### ISSUE THREAD

**Issue by novvere** [makespacemadrid/ApolloVentilator#73]
Crear un firmware que cambie la dirección I2C de un sensor de flujo SFM3xx.

**Comment by novvere** [comment]
El único documento que he encontrado que explica como hacerlo es para un sensor de líquidos, he preguntado al fabricante (Sensirion) como hacerlo.

**Comment by novvere** [comment]
Sensirion responde que en estos sensores no se puede cambiar la dirección I2C, hay que usar un multiplexor.

**Comment by novvere** [comment]
estamos usando una librería Software I2C para poder avanzar, tenemos que revisar los pines en los que se puede utilizar el el arduino uno. 
Si no hay dispositivo slave parece que se  bloquea, hay que revisar si se puede poner un timeout.

**Comment by novvere** [comment]
Los pines configurados para software I2C se corresponden con el número de pin dentro del puerto, es decir

```
#define SDA_PORT PORTC
#define SDA_PIN 2 
#define SCL_PORT PORTC
#define SCL_PIN 3
```

utiliza los pines A10 para SDA y A11 para SCL

Puedes definir, también antes de hacer el include..

`#define I2C_TIMEOUT 10000`

para que salte por timeout a los 10 segundos. El valor del timeout puede ir de 0 (no timeout) a 10000 (10 segundos)
En el arduino nano que Yo usé, conciden port c pin1 con A1 y portc pin2 con A2

**Comment by novvere** [comment]
No se puede cambiar la dirección del sensor y las pruebas realizadas con varias librerías I2C software dan muchos problemas. 
Optamos por usar un multiplexor  hardware

**Comment by balrog-kun** [comment]
Mientras se esperan nuevos componentes os recomiendo usar un esp32 como multiplexer.  En ESP32 tengo entendido existe I2C por hardware en los pines GPIO 21&22 pero a la libreria le dices en que pines la quieres instanciar y funciona independietemente de si son estos dos u otros, en mi prototipo usaba 3 buses I2C sin problema.
